package com.holat.login.models

data class Login(
    val SELFSERVICE_LOGIN_ENABLED: SELFSERVICELOGINENABLED,
    val SELFSERVICE_LOGIN_WITH_MOBILE: SELFSERVICELOGINWITHMOBILE,
    val SELFSERVICE_LOGIN_WITH_NATIONAL_ID: SELFSERVICELOGINWITHNATIONALID,
    val SELF_SERVICE_LOGIN_WAY: SELFSERVICELOGINWAY
)