package com.holat.login.models

data class THEME(
    val COPY_RIGHT_AR: COPYRIGHTAR,
    val COPY_RIGHT_EN: COPYRIGHTEN,
    val COPY_RIGHT_URL: COPYRIGHTURL,
    val FavIcon: FavIcon,
    val HEADER_COLOR: HEADERCOLOR,
    val HEADER_HOVER_COLOR: HEADERHOVERCOLOR,
    val LOGO: LOGO,
    val MINI_LOGO: MINILOGO,
    val SELF_SERVICE_DISPLAY_FONT_AR: SELFSERVICEDISPLAYFONTAR,
    val SELF_SERVICE_DISPLAY_FONT_EN: SELFSERVICEDISPLAYFONTEN,
    val SMALL_IMAGE: SMALLIMAGE
)